[build]
  command = "npm run build && cd server && npm install"
  publish = "web-build"
  functions = "server/netlify/functions"

[dev]
  command = "npm run build && cd server && npm install && netlify dev"
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
